import type { Metadata } from "next";
import localFont from "next/font/local";
import { auth } from "@auth";
import "./globals.css";
import { GlobalStoreProvider, ThemeStoreProvider } from "@/providers";
import { UserStoreProvider } from "@/providers/user";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`max-h-screen overflow-hidden max-w-screen ${geistSans.variable} ${geistMono.variable} antialiased theme-transition`}
        >
          {children}
        </body>
      </html>
    </Providers>
  );
}

async function Providers({ children }: { children: React.ReactNode }) {
  const session = await auth()
  const userInfo = session?.user

  return (
    <GlobalStoreProvider>
      <ThemeStoreProvider>
        <UserStoreProvider initData={userInfo}>
          {children}
        </UserStoreProvider>
      </ThemeStoreProvider >
    </GlobalStoreProvider >
  )
}